version: "3.8"  # Use a modern version

networks:
  app_network:

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  db:
    image: timescale/timescaledb:latest-pg15
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network

  api:
    build: ../api
    container_name: api
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - DB_HOST=${DB_HOST}
    networks:
      - app_network

  engine:
    build: ../engine
    container_name: engine
    depends_on:
      - redis
      - api
    environment:
      - REDIS_HOST=${REDIS_HOST}
    networks:
      - app_network

  ws:
    build: ../ws
    container_name: ws
    ports:
      - "3002:3002"
    depends_on:
      - redis
      - api
      - engine
    environment:
      - REDIS_HOST=${REDIS_HOST}
    networks:
      - app_network

  db_processor:
    build: ../db
    container_name: db_processor
    depends_on:
      - redis
      - db
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - DB_HOST=${DB_HOST}
    networks:
      - app_network

  mm:
    build: ../mm
    container_name: mm
    environment:
      - BACKEND_URL=${BACKEND_URL}
    networks:
      - app_network

volumes:
  db_data: